name = "avmgls"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "An AtomVM/gleam LED strip application using SPI"
target = "erlang"

licences = ["Apache-2.0"]
repository = { type = "github", user = "karlsson", repo = "avmgls" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

# gleam 1.9 supports github repositories
gleam = ">= 1.10.1"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
glydamic = { git = "https://github.com/karlsson/glydamic", ref="main"}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
atomvm_packgleam = { git = "https://github.com/karlsson/atomvm_packgleam", ref="main"}

## eensy_dev_tools = { path = "../eensy_dev_tools"}

## [eensy]
## platform = "esp32"
